src/Entity/Servicios.php
<?php

namespace App\Entity;

use App\Repository\ServiciosRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ServiciosRepository::class)]
class Servicios
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nombre = null;

    #[ORM\Column]
    private ?int $estado = null;

    #[ORM\Column]
    private array $metodos_pago = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): static
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getEstado(): ?int
    {
        return $this->estado;
    }

    public function setEstado(int $estado): static
    {
        $this->estado = $estado;

        return $this;
    }

    public function getMetodosPago(): array
    {
        return $this->metodos_pago;
    }

    public function setMetodosPago(array $metodos_pago): static
    {
        $this->metodos_pago = $metodos_pago;

        return $this;
    }
}

src/Form/ServiciosType.php
<?php

namespace App\Form;

use App\Entity\Servicios;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;


class ServiciosType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add(
                'nombre',
                TextType::class,
                [
                    'label' => 'Nombre del Servicio',
                    'required' => true,
                    'attr' => [
                        'size' => '150',
                        'class' => 'form-control',
                    ],
                ],
            )
            ->add(
                'estado',
                ChoiceType::class,
                [
                    'label' => 'Estado del Servicio',
                    'required' => true,
                    'multiple' => false,
                    'expanded' => false,
                    'choices' => [
                        'Activo' => '1',
                        'Inactivo' => '0',
                    ],
                    'attr' => [
                        'class' => 'form-control',
                    ],
                ],
            )
            ->add('metodos_pago', ChoiceType::class, [
                'choices' => $options['metodos_disponibles'], // Pasaremos los métodos disponibles como opción
                'choice_value' => 'id', // El valor que se enviará al formulario (el ID del método)
                'choice_label' => 'descripcion', // Lo que se mostrará al usuario (el nombre del método)
                'multiple' => true, // Permite seleccionar múltiples opciones
                'expanded' => true, // Muestra checkboxes en lugar de un select (opcional)
                'label' => 'Métodos de Pago Aceptados',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Servicios::class,
            'metodos_disponibles' => [], // Opción para pasar los métodos disponibles
        ]);

        // Asegúrate de que la opción 'metodos_disponibles' sea un array
        $resolver->setAllowedTypes('metodos_disponibles', 'array');
    }
}

src/Controller/ServiciosController.php
<?php

namespace App\Controller;

use App\Entity\Servicios;
use App\Form\ServiciosType;

use App\Entity\MetodoPago;
use App\Repository\ServiciosRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use DateTimeInterface;
use DateTime;

#[IsGranted('ROLE_ADMIN')] 
#[Route('/servicios')]
final class ServiciosController extends AbstractController
{

    #[Route(name: 'app_servicios_index', methods: ['GET'])]
    public function index(ServiciosRepository $serviciosRepository): Response
    {
        return $this->render('servicios/index.html.twig', [
            'servicios' => $serviciosRepository->findAll(),
            'logo'=>'assets/images/logo_vdesk1.png',
        ]);
    }

    #[Route('/new', name: 'app_servicios_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {

        
        $metodosRepository = $entityManager->getRepository(MetodoPago::class);
        $metodosDisponibles = $metodosRepository->findAll();        
        
        $servicio = new Servicios();
        $form = $this->createForm(
            ServiciosType::class, 
            $servicio,[
                'metodos_disponibles' => $metodosDisponibles,
            ]);
        $form->handleRequest($request);



        if ($form->isSubmitted() && $form->isValid()) {
            // tomamos del foprmulario lo que se selecciono como metodo de pago
            $selectedMetodoIds = $form->get('metodos_pago')->getData();
            dd ($selectedMetodoIds );

            $servicio->setMetodosPago($selectedMetodoIds);
            $entityManager->persist($servicio);
            $entityManager->flush();

            //return $this->redirectToRoute('app_servicios_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('servicios/new.html.twig', [
            'servicio' => $servicio,
            'form' => $form,
            'logo'=>'assets/images/logo_vdesk1.png',
        ]);
    }

    #[Route('/{id}', name: 'app_servicios_show', methods: ['GET'])]
    public function show(Servicios $servicio): Response
    {
        return $this->render('servicios/show.html.twig', [
            'servicio' => $servicio,
            'logo'=>'assets/images/logo_vdesk1.png',
        ]);
    }

    #[Route('/{id}/edit', name: 'app_servicios_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Servicios $servicio, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ServiciosType::class, $servicio);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_servicios_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('servicios/edit.html.twig', [
            'servicio' => $servicio,
            'form' => $form,
            'logo'=>'assets/images/logo_vdesk1.png',
        ]);
    }

    #[Route('/{id}', name: 'app_servicios_delete', methods: ['POST'])]
    public function delete(Request $request, Servicios $servicio, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$servicio->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($servicio);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_servicios_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/servicios/_delete_form.html.twig
<form method="post" action="{{ path('app_servicios_delete', {'id': servicio.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ servicio.id) }}">
    <button class="btn">Delete</button>
</form>

templates/servicios/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <div class="text-right">
        <button class="btn btn-primary">{{ button_label|default('Guardar') }}</button>
    </div>
{{ form_end(form) }}

templates/servicios/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Servicios{% endblock %}

{% block body %}
    <h1>Edit Servicios</h1>

    {{ include('servicios/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_servicios_index') }}">back to list</a>

    {{ include('servicios/_delete_form.html.twig') }}
{% endblock %}

templates/servicios/index.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Servicios registrados en el Sistema{% endblock %}

{% block body %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <button type="button" id="sidebarCollapse" class="btn btn-dark mr-2">
            <i class="fas fa-bars"></i>
        </button>
        <a class="navbar-brand" href="#">
            <img src="{{ logo }}" alt="Logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-user-circle mr-1"></i> Perfil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-cog mr-1"></i> Configuración</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/logout"><i class="fas fa-sign-out-alt mr-1"></i> Salir</a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- Sidebar -->
    {% include "bar_nav_dashboard_admin.html.twig" %}

    <!-- Contenido Principal -->
    <div id="content" style="padding:20px !important;">
        <div class="row">
            <div class='col-12 col-md-12 col-lg-12'>&nbsp;</div>
        </div>
        <div class="container-fluid p-4">
            <h2>Bienvenido al Sistema</h2>
            <p>Servicios registrados en el Sistema</p>
        </div>
        <div class="row">
            <div class='col-12 col-md-10 col-lg-10 text-right' style="margin: auto !important;">
                <a href="{{ path('app_servicios_new') }}" title="Crear un nuevo Método de Pago"><i class="fas fa-plus-square"></i></a>
            </div>
        </div>      
        <div class="row">
            <div class='col-12 col-md-10 col-lg-10' style="margin: auto !important;">
                <table class="table table-striped">
                    <thead class='bg-secondary text-center'>
                        <tr>
                            <th>Id</th>
                            <th>Nombre</th>
                            <th>Estado</th>
                            <th>Metodos_pago</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for servicio in servicios %}
                        <tr>
                            <td>{{ servicio.id }}</td>
                            <td>{{ servicio.nombre }}</td>
                            <td class='text-center'>
                                {% if ( servicio.estado == 1 ) %}
                                    Activo
                                {% else %}
                                    Inactivo
                                {% endif %}    
                            </td>
                            <td>{{ servicio.metodosPago ? servicio.metodosPago|json_encode : '' }}</td>
                            <td>
                                <a href="{{ path('app_servicios_edit', {'id': servicio.id}) }}"><i class="fas fa-edit"></i></a>
                                <a href="{{ path('app_servicios_delete', {'id':servicio.id}) }}"><i class="fas fa-trash-alt"></i></a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="5" class='text-danger'>No se encontrraron Servicios registrados en el sistema</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class='col-12 col-md-10 col-lg-10 text-right' style="margin: auto !important;">
                <a href="{{ path('app_servicios_new') }}" title="Crear un nuevo Método de Pago"><i class="fas fa-plus-square"></i></a>
            </div>
        </div>        
    </div>
{% endblock %}

templates/servicios/new.html.twig
{% extends 'base2.html.twig' %}

{% block title %}Crear un Servicio{% endblock %}

{% block body %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <button type="button" id="sidebarCollapse" class="btn btn-dark mr-2">
            <i class="fas fa-bars"></i>
        </button>
        <a class="navbar-brand" href="#">
            <img src="../{{ logo }}" alt="Logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-user-circle mr-1"></i> Perfil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-cog mr-1"></i> Configuración</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-sign-out-alt mr-1"></i> Salir</a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- Sidebar -->
    {% include "bar_nav_dashboard_admin.html.twig" %}

    <!-- Contenido Principal -->
    <div id="content" style="padding:20px !important">
        <div class="row" style="padding-top: 20px !important">
            <div class="col-12 col-md-8 col-lg-8" style="margin:auto !important" >
                &nbsp;          
            </div>
        </div>    
        <div class="row">
            <div class="col-12 col-md-8 col-lg-8" style="margin:auto !important" >
                <div class="text-right"><a href="{{ path('app_servicios_index') }}" title="Regresar al listado"><i class="fas fa-list-ol"></i></a></div>
                <div class="card shadow">
                    <div class="card-header text-center"><h4>Crea una nuevo Servicio</h4></div>
                    <div class="card-body">                
                        {{ include('servicios/_form.html.twig') }}
                    </div>
                </div>
                <div class="text-right"><a href="{{ path('app_servicios_index') }}" title="Regresar al listado"><i class="fas fa-list-ol"></i></a></div>
            </div>
        </div>

    </div>
{% endblock %}

templates/servicios/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Servicios{% endblock %}

{% block body %}
    <h1>Servicios</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ servicio.id }}</td>
            </tr>
            <tr>
                <th>Nombre</th>
                <td>{{ servicio.nombre }}</td>
            </tr>
            <tr>
                <th>Estado</th>
                <td>{{ servicio.estado }}</td>
            </tr>
            <tr>
                <th>Metodos_pago</th>
                <td>{{ servicio.metodosPago ? servicio.metodosPago|json_encode : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_servicios_index') }}">back to list</a>

    <a href="{{ path('app_servicios_edit', {'id': servicio.id}) }}">edit</a>

    {{ include('servicios/_delete_form.html.twig') }}
{% endblock %}