src/Entity/JobOffers.php
<?php

namespace App\Entity;

use App\Repository\JobOffersRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: JobOffersRepository::class)]
class JobOffers
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Empresa $empresa = null;

    #[ORM\Column(length: 255)]
    private ?string $titulo = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $descripcion = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $fecha_publicacion = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $fecha_finalizacion = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $fecha_atencion = null;

    #[ORM\Column]
    private ?int $estado = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Categorias $categoria = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmpresa(): ?Empresa
    {
        return $this->empresa;
    }

    public function setEmpresa(?Empresa $empresa): static
    {
        $this->empresa = $empresa;

        return $this;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): static
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(string $descripcion): static
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getFechaPublicacion(): ?\DateTimeInterface
    {
        return $this->fecha_publicacion;
    }

    public function setFechaPublicacion(\DateTimeInterface $fecha_publicacion): static
    {
        $this->fecha_publicacion = $fecha_publicacion;

        return $this;
    }

    public function getFechaFinalizacion(): ?\DateTimeInterface
    {
        return $this->fecha_finalizacion;
    }

    public function setFechaFinalizacion(\DateTimeInterface $fecha_finalizacion): static
    {
        $this->fecha_finalizacion = $fecha_finalizacion;

        return $this;
    }

    public function getFechaAtencion(): ?\DateTimeInterface
    {
        return $this->fecha_atencion;
    }

    public function setFechaAtencion(?\DateTimeInterface $fecha_atencion): static
    {
        $this->fecha_atencion = $fecha_atencion;

        return $this;
    }

    public function getEstado(): ?int
    {
        return $this->estado;
    }

    public function setEstado(int $estado): static
    {
        $this->estado = $estado;

        return $this;
    }

    public function getCategoria(): ?Categorias
    {
        return $this->categoria;
    }

    public function setCategoria(?Categorias $categoria): static
    {
        $this->categoria = $categoria;

        return $this;
    }
}

src/Form/JobOffersType.php
<?php

namespace App\Form;

use App\Entity\Categorias;
use App\Entity\Empresa;
use App\Entity\JobOffers;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class JobOffersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titulo')
            ->add('descripcion')
            ->add('fecha_publicacion', null, [
                'widget' => 'single_text',
            ])
            ->add('fecha_finalizacion', null, [
                'widget' => 'single_text',
            ])
            ->add('fecha_atencion', null, [
                'widget' => 'single_text',
            ])
            ->add('estado')
            ->add('empresa', EntityType::class, [
                'class' => Empresa::class,
                'choice_label' => 'id',
            ])
            ->add('categoria', EntityType::class, [
                'class' => Categorias::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => JobOffers::class,
        ]);
    }
}

src/Controller/JobOffersController.php
<?php

namespace App\Controller;

use App\Entity\JobOffers;
use App\Entity\Empresa;
use App\Form\JobOffersType;
use App\Repository\JobOffersRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use DateTimeInterface;
use DateTime;



#[Route('/job_offers')]
final class JobOffersController extends AbstractController
{
    #[IsGranted('ROLE_USER')] 
    #[Route(name: 'app_job_offers_index', methods: ['GET'])]
    public function index(JobOffersRepository $jobOffersRepository): Response
    {
        return $this->render('job_offers/index.html.twig', [
            'job_offers' => $jobOffersRepository->findAll(),
            'logo'=>'assets/images/logo_vdesk1.png',
        ]);
    }

    #[IsGranted('ROLE_ADMIN')] 
    #[Route('/admin_list',name: 'app_job_offers_list_admin', methods: ['GET'])]
    public function listAdmin(JobOffersRepository $jobOffersRepository): Response
    {
        return $this->render('job_offers/list.html.twig', [
            'job_offers' => $jobOffersRepository->findAll(),
            'logo'=>'assets/images/logo_vdesk1.png',
        ]);
    }

    #[IsGranted('ROLE_USER')] 
    #[Route('/new', name: 'app_job_offers_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $jobOffer = new JobOffers();
        $form = $this->createForm(JobOffersType::class, $jobOffer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($jobOffer);
            $entityManager->flush();

            return $this->redirectToRoute('app_job_offers_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('job_offers/new.html.twig', [
            'job_offer' => $jobOffer,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_USER')] 
    #[IsGranted('ROLE_ADMIN')] 
    #[Route('/{id}', name: 'app_job_offers_show', methods: ['GET'])]
    public function show(JobOffers $jobOffer): Response
    {
        return $this->render('job_offers/show.html.twig', [
            'job_offer' => $jobOffer,
        ]);
    }

    #[IsGranted('ROLE_USER')] 
    #[Route('/{id}/edit', name: 'app_job_offers_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, JobOffers $jobOffer, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(JobOffersType::class, $jobOffer);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_job_offers_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('job_offers/edit.html.twig', [
            'job_offer' => $jobOffer,
            'form' => $form,
        ]);
    }

    #[IsGranted('ROLE_USER')] 
    #[IsGranted('ROLE_ADMIN')] 
    #[Route('/{id}', name: 'app_job_offers_delete', methods: ['POST'])]
    public function delete(Request $request, JobOffers $jobOffer, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$jobOffer->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($jobOffer);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_job_offers_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/job_offers/_delete_form.html.twig
<form method="post" action="{{ path('app_job_offers_delete', {'id': job_offer.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ job_offer.id) }}">
    <button class="btn">Delete</button>
</form>

templates/job_offers/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/job_offers/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit JobOffers{% endblock %}

{% block body %}
    <h1>Edit JobOffers</h1>

    {{ include('job_offers/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_job_offers_index') }}">back to list</a>

    {{ include('job_offers/_delete_form.html.twig') }}
{% endblock %}

templates/job_offers/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}JobOffers index{% endblock %}

{% block body %}
    <h1>JobOffers index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titulo</th>
                <th>Descripcion</th>
                <th>Fecha_publicacion</th>
                <th>Fecha_finalizacion</th>
                <th>Fecha_atencion</th>
                <th>Estado</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for job_offer in job_offers %}
            <tr>
                <td>{{ job_offer.id }}</td>
                <td>{{ job_offer.titulo }}</td>
                <td>{{ job_offer.descripcion }}</td>
                <td>{{ job_offer.fechaPublicacion ? job_offer.fechaPublicacion|date('Y-m-d') : '' }}</td>
                <td>{{ job_offer.fechaFinalizacion ? job_offer.fechaFinalizacion|date('Y-m-d') : '' }}</td>
                <td>{{ job_offer.fechaAtencion ? job_offer.fechaAtencion|date('Y-m-d') : '' }}</td>
                <td>{{ job_offer.estado }}</td>
                <td>
                    <a href="{{ path('app_job_offers_show', {'id': job_offer.id}) }}">show</a>
                    <a href="{{ path('app_job_offers_edit', {'id': job_offer.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="8">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_job_offers_new') }}">Create new</a>
{% endblock %}

templates/job_offers/list.html.twig
{% extends 'base2.html.twig' %}

{% block title %}OSolicitidues de las Empresas Afiliadas{% endblock %}

{% block body %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <button type="button" id="sidebarCollapse" class="btn btn-dark mr-2">
            <i class="fas fa-bars"></i>
        </button>
        <a class="navbar-brand" href="#">
            <img src="{{ logo }}" alt="Logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-user-circle mr-1"></i> Perfil</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><i class="fas fa-cog mr-1"></i> Configuración</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/logout"><i class="fas fa-sign-out-alt mr-1"></i> Salir</a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- Sidebar -->
    {% include "bar_nav_dashboard_admin.html.twig" %}

    <!-- Contenido Principal -->
    <div id="content" style="padding:20px !important;">
        <div class="row">
            <div class='col-12 col-md-12 col-lg-12'>&nbsp;</div>
        </div>
        <div class="container-fluid p-4">
            <h2>Bienvenido al Sistema</h2>
            <p>Solicitudes Registradas</p>
        </div>
        <div class="row">
            <div class='col-12 col-md-10 col-lg-10' style="margin: auto !important;">
                <table class="table">
                    <thead>
                        <tr>
                            <th>Id</th>
                            <th>Titulo</th>
                            <th>Descripcion</th>
                            <th>Fecha_publicacion</th>
                            <th>Fecha_finalizacion</th>
                            <th>Fecha_atencion</th>
                            <th>Estado</th>
                            <th>actions</th>
                        </tr>
                    </thead>
                    <tbody>
                    {% for job_offer in job_offers %}
                        <tr>
                            <td>{{ job_offer.id }}</td>
                            <td>{{ job_offer.titulo }}</td>
                            <td>{{ job_offer.descripcion }}</td>
                            <td>{{ job_offer.fechaPublicacion ? job_offer.fechaPublicacion|date('Y-m-d') : '' }}</td>
                            <td>{{ job_offer.fechaFinalizacion ? job_offer.fechaFinalizacion|date('Y-m-d') : '' }}</td>
                            <td>{{ job_offer.fechaAtencion ? job_offer.fechaAtencion|date('Y-m-d') : '' }}</td>
                            <td>{{ job_offer.estado }}</td>
                            <td>
                                <a href="{{ path('app_job_offers_show', {'id': job_offer.id}) }}">show</a>
                                <a href="{{ path('app_job_offers_edit', {'id': job_offer.id}) }}">edit</a>
                            </td>
                        </tr>
                    {% else %}
                        <tr>
                            <td colspan="8" class='text-danger'>No se han registrado solicitudes</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

templates/job_offers/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New JobOffers{% endblock %}

{% block body %}
    <h1>Create new JobOffers</h1>

    {{ include('job_offers/_form.html.twig') }}

    <a href="{{ path('app_job_offers_index') }}">back to list</a>
{% endblock %}

templates/job_offers/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}JobOffers{% endblock %}

{% block body %}
    <h1>JobOffers</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ job_offer.id }}</td>
            </tr>
            <tr>
                <th>Titulo</th>
                <td>{{ job_offer.titulo }}</td>
            </tr>
            <tr>
                <th>Descripcion</th>
                <td>{{ job_offer.descripcion }}</td>
            </tr>
            <tr>
                <th>Fecha_publicacion</th>
                <td>{{ job_offer.fechaPublicacion ? job_offer.fechaPublicacion|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Fecha_finalizacion</th>
                <td>{{ job_offer.fechaFinalizacion ? job_offer.fechaFinalizacion|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Fecha_atencion</th>
                <td>{{ job_offer.fechaAtencion ? job_offer.fechaAtencion|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Estado</th>
                <td>{{ job_offer.estado }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_job_offers_index') }}">back to list</a>

    <a href="{{ path('app_job_offers_edit', {'id': job_offer.id}) }}">edit</a>

    {{ include('job_offers/_delete_form.html.twig') }}
{% endblock %}